### ISSUE TITLE
Нарушение авторских прав 

### ISSUE THREAD

**Issue by JimmDiGrizli** [sasgis/sas.maps#5]
Уважаемый авторы проекта!

Мы обнаружили, что Вами выложены карты издания ООО «СЗ РЦАИ» в растровом виде на сервисе SASGIS, а также мы обнаружили модуль подключения наших карт к ГИС-системам на сайте github.com. Данные карты являются собственностью ООО «СЗ РЦАИ» и не распространяются бесплатно.

Предлагаем Вам до 15 июня 2020 года удалить карты и модуль подключения с указанных ресурсов, удалить карты с Ваших серверов/сервера.

В противном случае мы будем вынуждены обратиться в органы прокуратуры с заявлением о нарушении Вами авторских прав, и причинении тем самым материального ущерба ООО «СЗ РЦАИ».

По интересующим Вас вопросам, а также в случае Вашей заинтересованности во взаимовыгодном сотрудничестве, Вы можете обращаться в наш адрес любым удобным способом указанным на [нашем сайте](https://www.szrcai.ru/about).

**Comment by zedxxx** [comment]
О каком zmp идёт речь и где на sasgis.org выложены растры?

Всё что касается сайта программы, обращайтесь напрямую к его администратору (Parasite). Авторы программы сайт не контролируют.

**Comment by JimmDiGrizli** [comment]
В вашем проекте авторское право нарушает данный файл, просим его удалить:
https://github.com/sasgis/sas.maps/tree/master/_aviation/baionline2.zmp

**Comment by zedxxx** [comment]
Удалил. Вопрос закрыт?

**Comment by JimmDiGrizli** [comment]
Закрыт.
Спасибо за оперативность.
